blank_issues_enabled: false
contact_links:
  - name: Emergency Contact
    url: mailto:admin@rhssoccer.org
    about: For urgent matters requiring immediate attention (game day issues, safety concerns)
  - name: General Questions
    url: mailto:info@rhssoccer.org
    about: For general inquiries that don't require issue tracking
  - name: Documentation
    url: https://github.com/yourusername/rhs-soccer-feedback/wiki
    about: Check our documentation for common solutions and guides