blank_issues_enabled: false
contact_links:
  - name: Emergency Contact
    url: mailto:admin@gojjoapps.com
    about: For urgent matters requiring immediate attention (game day issues, safety concerns)
  - name: General Questions
    url: mailto:info@gojjoapps.com
    about: For general inquiries that don't require issue tracking
  - name: Documentation
    url: https://app.rhsboyssoccer.com/help
    about: Check our documentation for common solutions and guides